name = "MatrixProductStates"
uuid = "5fe0d8d6-e987-11e8-0432-21eb125b105c"
authors = ["andreas <andreas.peter.ch@gmail.com>"]
version = "0.1.0"

[deps]
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
TensorNetworkTensors = "9cd545fa-50e6-5d0b-b05c-fbfd5125ba2b"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
